#
#spring:
#  mvc:
#    static-path-pattern: /res/**

#  web:
#    resources:
#      static-locations: [classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/zhang/]spring: